apiVersion: v1
kind: Service
metadata:
  name: liveness-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8081"
spec:
  type: LoadBalancer
  selector:
    app: liveness-app
  ports:
    - port: 80
      targetPort: 8081
