server.port=8081
# for Kubernetes liveness and readiness probes
management.endpoint.health.probes.enabled=true
# exposed endpoints
management.endpoints.web.exposure.include=health, info, metrics, env, beans
# add build info to /actuator/info
management.info.build.enabled=true
management.info.git.enabled=true
# always show details, or only when authenticated
management.endpoint.health.show-details=always
spring.application.name=liveness
# readiness probe should wait for 20 seconds before timing out, to give the application enough time to start up
spring.lifecycle.timeout-per-shutdown-phase=20s
# at /actuator/health/liveness
management.health.livenessState.enabled=true
# at /actuator/health/readiness
management.health.readinessState.enabled=true